version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/damien-side.fun.gateway:${IMAGE_TAG}
        restart: always
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt:ro
          - /var/www/html:/var/www/html:ro
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - frontend
          - api

    frontend:
        image: ${REGISTRY}/damien-side.fun.frontend:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/damien-side.fun.api:${IMAGE_TAG}
        restart: always
        depends_on:
          - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/damien-side.fun.php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls

    api-php-cli:
        image: ${REGISTRY}/damien-side.fun.php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: tls
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro

    api-postgres:
        image: postgres:12.2-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
      volumes:
        - api-postgres:/var/lib/postgresql/data

volumes:
    api-postgres: