version: "3.7"
services:
    gateway:
        image: ${REGISTRY}/damien-gateway:${IMAGE_TAG}
        restart: always
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt:ro
          - /var/www/html:/var/www/html:ro
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - frontend
          - api

    frontend:
        image: ${REGISTRY}/damien-front:${IMAGE_TAG}
        restart: always

    api:
        image: ${REGISTRY}/damien-api:${IMAGE_TAG}
        restart: always
        depends_on:
          - api-php-fpm

    api-php-fpm:
        image: ${REGISTRY}/damien-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_ENV: prod
            APP_DEBUG: 0

    api-php-cli:
        image: ${REGISTRY}/damien-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0